// do not edit this file - automatically generated during build
// regenerated at 2023-06-30 07:01:42.038643

#define VERSION_BRANCH "hh-main"

#define VERSION_COMMIT_HASH "4fa2784"

#define VERSION_COMMIT_STATUS "dirty"

#define VERSION_BUILD "hh-main 4fa2784 (dirty)"

